[theme]
base = "light"
primaryColor = "#1E46B8"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#17202E"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"
