[theme]
primaryColor = "#06776f"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#172b40"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"
